### ISSUE TITLE
Path null

### ISSUE THREAD

**Issue by Lypzis** [mikewesthad/phaser-navmesh#2]
the path is always null no matter what points I put in 'findPath' method, now I don't know if my tableGround-map.json(attached, extension modified just to fit here)
[tableGround-map.txt](https://github.com/mikewesthad/phaser-navmesh/files/1961647/tableGround-map.txt)

 is wrong or is the plugin. here is what shows in the console:

buildNavMesh():
`t {game: i.Game, _debugGraphics: null, _meshShrinkAmount: 5, _navPolygons: Array(0), _graph: t}`

findPath():
`null`

**Comment by mikewesthad** [comment]
@Lypzis, hm - could you share a code snippet so I can see how you are setting up and using the plugin? 

Does it fail to find a path even for points within the same Tiled rectangle - e.g. (30, 30) -> (60, 60)?

Also, you could use the debugging graphics to see what the plugin is detecting as connected neighbors:

```js
navMesh.enableDebug(); // Creates a Phaser.Graphics overlay on top of the screen
navMesh.debugClear(); // Clears the overlay
// Visualize the underlying navmesh
navMesh.debugDrawMesh({
    drawCentroid: true, drawBounds: false, drawNeighbors: true, drawPortals: true
});
```

**Comment by Lypzis** [comment]
I don't know how to do a snippet, but here is my repository code where I'm testing the plugin:
https://github.com/Lypzis/Conquer_Them_All/tree/test

the debugging graphics doesn't show anything.

the file where the plugin setup and usage are:
 src/states/TheGame.js
https://github.com/Lypzis/Conquer_Them_All/blob/test/src/states/TheGame.js

to run:
npm run electron

**Comment by mikewesthad** [comment]
Thanks for sharing. I didn't run it, but you've got a typo [here](https://github.com/Lypzis/Conquer_Them_All/blob/test/src/states/TheGame.js#L37). It should be `navmesh` - not `navMesh` - in order to match what you named your object layer in the tableGround-map file.

**Comment by mikewesthad** [comment]
I added some console messages to help warn devs when situations like this would arise. I'm going to close this issue for now, but definitely let me know if this didn't fix it.
